name: Playwright Tests

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Ejecutar las pruebas de Playwright
      - name: Run Playwright tests
        run: npx playwright test --reporter=junit --output test-results
        continue-on-error: true # Permitir que el flujo continúe si hay fallos

      # 5. Subir los resultados como un artefacto
      - name: Upload test results
        if: always() # Siempre subir resultados, incluso si fallaron las pruebas
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: test-results

      # 6. Generar anotaciones basadas en los resultados
      - name: Create annotations from JUnit results
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'test-results/*.xml' # Ruta a los reportes generados por Playwright
          check_name: 'Playwright Test Results'
          require_tests: true
