name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests and output results
      id: test
      run: |
        npx playwright test --reporter=json > result.json
        echo "::set-output name=result::$(cat result.json)"

    - name: Add annotations for test results
      run: |
        RESULT=$(cat result.json)
        for test_case in $(echo "$RESULT" | jq -r '.suites[].tests[] | @base64'); do
          _jq() {
            echo ${test_case} | base64 --decode | jq -r ${1}
          }
          name=$(_jq '.title')
          status=$(_jq '.status')
          file=$(_jq '.location.file')
          line=$(_jq '.location.line')

          if [[ "$status" == "failed" ]]; then
            echo "::error file=${file},line=${line}::Test '${name}' failed"
          elif [[ "$status" == "skipped" ]]; then
            echo "::warning file=${file},line=${line}::Test '${name}' was skipped"
          else
            echo "::notice file=${file},line=${line}::Test '${name}' passed"
          fi
        done
