name: Playwright Tests

on:
  pull_request:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Find test files
        id: set-matrix
        run: |
          FILES=$(find tests -name "*.spec.ts")
          MATRIX=$(echo $FILES | jq -R -s -c 'split("\n") | map(select(length > 0)) | {file: .}')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright test
        run: |
          npx playwright test ${{ matrix.file }} --reporter=junit --output test-results

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file }}-results
          path: test-results

      - name: Create annotations for test
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'test-results/*.xml'
          check_name: 'Playwright Test: ${{ matrix.file }}'
          require_tests: true
